import { IMAGES } from "../assets";

export const data = [
  {
    id: 1,

    name: "HERE&NOW",
    size: ["38", "40", "42", "44"],
    rating: "4.3",
    buyers: "11.1k",
    price: "799",
    discount: "(60% OFF)",
    cutprice: "1999",
    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img1,
    gender: "male",
  },
  {
    id: 2,

    name: "Roadster",
    size: ["38", "40", "42", "44"],
    rating: "4.4",
    buyers: "21.5k",
    price: "449",
    discount: "(55% OFF)",
    cutprice: "999",
    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img2,
    gender: "male",
  },
  {
    id: 3,

    name: "Her By invictus",
    size: ["38", "40", "42", "44"],
    rating: "4.4",
    buyers: "665",
    price: "899",
    discount: "(55% OFF)",
    cutprice: "1999",
    desc: "Women Casual Shirt",
    image: IMAGES.img3,
    gender: "female",
  },
  {
    id: 4,

    name: "Mast & Hobour",
    size: ["38", "40", "42", "44"],
    rating: "4.3",
    buyers: "345",
    price: "659",
    discount: "(45% OFF)",
    cutprice: "1999",
    desc: "Semi-Sheer Casual Shirt",
    image: IMAGES.img4,
    gender: "female",
  },
  {
    id: 5,

    name: "Roadster",
    size: ["38", "40", "42", "44"],
    rating: "4.4",
    buyers: "6.4k",
    price: "674",
    discount: "(55% OFF)",
    cutprice: "1499",
    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img5,
    gender: "male",
  },
  {
    id: 6,

    name: "Roadster",
    size: ["38", "40", "42", "44"],
    rating: "4.2",
    buyers: "10.8k",
    price: "674",
    discount: "(55% OFF)",
    cutprice: "1499",
    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img6,
    gender: "male",
  },
  {
    id: 7,

    name: "Danish Lingo",
    size: ["38", "40", "42", "44"],
    rating: "4.1",
    buyers: "8.9k",
    price: "665",
    discount: "(64% OFF)",
    cutprice: "1849",
    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img7,
    gender: "male",
  },
  {
    id: 8,

    name: "SASSAFRAS",
    size: ["38", "40", "42", "44"],
    rating: "4.4",
    buyers: "2.8k",
    price: "519",
    discount: "(60% OFF)",
    cutprice: "1299",
    desc: "Dobby Sheer Boxy Shirt",
    image: IMAGES.img8,
    gender: "female",
  },
  {
    id: 9,

    name: "HERE&NOW",
    size: ["38", "40", "42", "44"],
    rating: "4.4",
    buyers: "3.5k",
    price: "854",
    discount: "(55% OFF)",
    cutprice: "1899",
    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img9,
    gender: "male",
  },
  {
    id: 10,
    name: "Roadster",
    size: ["38", "40", "42", "44"],
    rating: "4.4",
    buyers: "7.8k",
    price: "674",
    discount: "(55% OFF)",
    cutprice: "1499",
    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img10,
    gender: "male",
  },
  {
    id: 11,
    name: "H&M",
    size: ["38", "40", "42", "44"],
    rating: "4.6",
    buyers: "14",
    price: "909",
    discount: "(30% OFF)",
    cutprice: "1299",

    desc: "Women Checked Shirt",
    image: IMAGES.img11,
    gender: "female",
  },
  {
    id: 12,
    name: "SASSAFRAS",
    size: ["38", "40", "42", "44"],
    rating: "4.4",
    buyers: "5.3k",
    price: "584",
    discount: "(55% OFF)",
    cutprice: "1299",

    desc: "Dobby Sheer Boxy Shirt",
    image: IMAGES.img12,
    gender: "female",
  },
  {
    id: 13,
    name: "The Indian Garage Co",
    size: ["38", "40", "42", "44"],
    rating: "4",
    buyers: "2.5",
    price: "610",
    discount: "(63% OFF)",
    cutprice: "1649",
    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img13,
    gender: "male",
  },
  {
    id: 14,
    name: "Nautica",
    size: ["38", "40", "42", "44"],
    rating: "4.6",
    buyers: "22",
    price: "2199",
    discount: "(45% OFF)",
    cutprice: "3999",

    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img14,
    gender: "male",
  },
  {
    id: 15,
    name: "Tokyo Talkies",
    size: ["38", "40", "42", "44"],
    rating: "4.2",
    buyers: "486",
    price: "549",
    discount: "(60% OFF)",
    cutprice: "1149",

    desc: "Regular Fit Casual Shirt",
    image: IMAGES.img15,
    gender: "female",
  },
  {
    id: 16,
    name: "HIGHLANDER",
    size: ["38", "40", "42", "44"],
    rating: "4.1",
    buyers: "6.9k",
    price: "629",
    discount: "(37% OFF)",
    cutprice: "999",

    desc: "Men Slim Fit Casual Shirt",
    image: IMAGES.img16,
    gender: "male",
  },
  {
    id: 17,
    name: "HIGHLANDER",
    size: ["38", "40", "42", "44"],
    rating: "4.1",
    buyers: "6.9k",
    price: "599",
    discount: "(40% OFF)",
    cutprice: "999",

    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img17,
    gender: "male",
  },
  {
    id: 18,
    name: "All about you",
    size: ["38", "40", "42", "44"],
    rating: "4.2",
    buyers: "722",
    price: "644",
    discount: "(57% OFF)",
    cutprice: "1499",

    desc: "Slim Fit Casual Shirt",
    image: IMAGES.img18,
    gender: "female",
  },
  {
    id: 19,
    name: "WROGN",
    size: ["38", "40", "42", "44"],
    rating: "4.1",
    buyers: "4.6k",
    price: "1499",
    discount: "(40% OFF)",
    cutprice: "2499",

    desc: "Slim Fit Casual Shirt",
    image: IMAGES.img19,
    gender: "male",
  },
  {
    id: 20,
    name: "HIGHLANDER",
    size: ["38", "40", "42", "44"],
    rating: "4.3",
    buyers: "3.2k",
    price: "439",
    discount: "(60% OFF)",
    cutprice: "1099",

    desc: "Slim Fit Casual Shirt",
    image: IMAGES.img20,
    gender: "male",
  },
];
