import { IMAGES } from "../assets";

export const data = [
  {
    id: 1,

    name: "HERE&NOW",
    size: ["38", "40", "42", "44"],
    rating: "4.3",
    buyers: "11.1k",
    price: "799",
    discount: "(60% OFF)",
    cutprice: "1999",
    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img1,
    username: "Safak Kocaoglu",
  },
  {
    id: 2,

    name: "Roadster",
    size: ["38", "40", "42", "44"],
    rating: "4.4",
    buyers: "21.5k",
    price: "449",
    discount: "(55% OFF)",
    cutprice: "999",
    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img2,
    username: "Janell Shrum",
  },
  {
    id: 3,

    name: "Her By invictus",
    size: ["38", "40", "42", "44"],
    rating: "4.4",
    buyers: "665",
    price: "899",
    discount: "(55% OFF)",
    cutprice: "1999",
    desc: "Women Casual Shirt",
    image: IMAGES.img3,
    username: "Alex Durden",
  },
  {
    id: 4,

    name: "Mast & Hobour",
    size: ["38", "40", "42", "44"],
    rating: "4.3",
    buyers: "345",
    price: "659",
    discount: "(45% OFF)",
    cutprice: "1999",
    desc: "Semi-Sheer Casual Shirt",
    image: IMAGES.img4,
    username: "Dora Hawks",
  },
  {
    id: 5,

    name: "Roadster",
    size: ["38", "40", "42", "44"],
    rating: "4.4",
    buyers: "6.4k",
    price: "674",
    discount: "(55% OFF)",
    cutprice: "1499",
    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img5,
    username: "Thomas Holden",
  },
  {
    id: 6,

    name: "Roadster",
    size: ["38", "40", "42", "44"],
    rating: "4.2",
    buyers: "10.8k",
    price: "674",
    discount: "(55% OFF)",
    cutprice: "1499",
    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img6,
    username: "Shirley Beauchamp",
  },
  {
    id: 7,

    name: "Danish Lingo",
    size: ["38", "40", "42", "44"],
    rating: "4.1",
    buyers: "8.9k",
    price: "665",
    discount: "(64% OFF)",
    cutprice: "1849",
    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img7,
    username: "Travis Bennett",
  },
  {
    id: 8,

    name: "SASSAFRAS",
    size: ["38", "40", "42", "44"],
    rating: "4.4",
    buyers: "2.8k",
    price: "519",
    discount: "(60% OFF)",
    cutprice: "1299",
    desc: "Dobby Sheer Boxy Shirt",
    image: IMAGES.img8,
    username: "Kristen Thomas",
  },
  {
    id: 9,

    name: "HERE&NOW",
    size: ["38", "40", "42", "44"],
    rating: "4.4",
    buyers: "3.5k",
    price: "854",
    discount: "(55% OFF)",
    cutprice: "1899",
    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img9,
    username: "Gary Duty",
  },
  {
    id: 10,
    name: "Roadster",
    size: ["38", "40", "42", "44"],
    rating: "4.4",
    buyers: "7.8k",
    price: "674",
    discount: "(55% OFF)",
    cutprice: "1499",
    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img10,
    username: "Safak Kocaoglu",
  },
  {
    id: 11,
    name: "H&M",
    size: ["38", "40", "42", "44"],
    rating: "4.6",
    buyers: "14",
    price: "909",
    discount: "(30% OFF)",
    cutprice: "1299",

    desc: "Women Checked Shirt",
    image: IMAGES.img11,
    username: "Safak Kocaoglu",
  },
  {
    id: 12,
    name: "SASSAFRAS",
    size: ["38", "40", "42", "44"],
    rating: "4.4",
    buyers: "5.3k",
    price: "584",
    discount: "(55% OFF)",
    cutprice: "1299",

    desc: "Dobby Sheer Boxy Shirt",
    image: IMAGES.img12,
    username: "Janell Shrum",
  },
  {
    id: 13,
    name: "The Indian Garage Co",
    size: ["38", "40", "42", "44"],
    rating: "4",
    buyers: "2.5",
    price: "610",
    discount: "(63% OFF)",
    cutprice: "1649",
    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img13,
    username: "Alex Durden",
  },
  {
    id: 14,
    name: "Nautica",
    size: ["38", "40", "42", "44"],
    rating: "4.6",
    buyers: "22",
    price: "2199",
    discount: "(45% OFF)",
    cutprice: "3999",

    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img14,
    username: "Dora Hawks",
  },
  {
    id: 15,
    name: "Tokyo Talkies",
    size: ["38", "40", "42", "44"],
    rating: "4.2",
    buyers: "486",
    price: "549",
    discount: "(60% OFF)",
    cutprice: "1149",

    desc: "Regular Fit Casual Shirt",
    image: IMAGES.img15,
    username: "Thomas Holden",
  },
  {
    id: 16,
    name: "HIGHLANDER",
    size: ["38", "40", "42", "44"],
    rating: "4.1",
    buyers: "6.9k",
    price: "629",
    discount: "(37% OFF)",
    cutprice: "999",

    desc: "Men Slim Fit Casual Shirt",
    image: IMAGES.img16,
    username: "Shirley Beauchamp",
  },
  {
    id: 17,
    name: "HIGHLANDER",
    size: ["38", "40", "42", "44"],
    rating: "4.1",
    buyers: "6.9k",
    price: "599",
    discount: "(40% OFF)",
    cutprice: "999",

    desc: "Men Casual Cotton Shirt",
    image: IMAGES.img17,
    username: "Travis Bennett",
  },
  {
    id: 18,
    name: "All about you",
    size: ["38", "40", "42", "44"],
    rating: "4.2",
    buyers: "722",
    price: "644",
    discount: "(57% OFF)",
    cutprice: "1499",

    desc: "Slim Fit Casual Shirt",
    image: IMAGES.img18,
    username: "Kristen Thomas",
  },
  {
    id: 19,
    name: "WROGN",
    size: ["38", "40", "42", "44"],
    rating: "4.1",
    buyers: "4.6k",
    price: "1499",
    discount: "(40% OFF)",
    cutprice: "2499",

    desc: "Slim Fit Casual Shirt",
    image: IMAGES.img19,
    username: "Gary Duty",
  },
  {
    id: 20,
    name: "HIGHLANDER",
    size: ["38", "40", "42", "44"],
    rating: "4.3",
    buyers: "3.2k",
    price: "439",
    discount: "(60% OFF)",
    cutprice: "1099",

    desc: "Slim Fit Casual Shirt",
    image: IMAGES.img20,
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
